spring.application.name=Mind_Ease

spring.datasource.url=jdbc:mysql://localhost:3306/iste240
spring.datasource.username=root
spring.datasource.password=abc1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect